### ISSUE TITLE
Producing exactly the same results as TEcount

### ISSUE THREAD

**Issue by xunchen85** [mhammell-laboratory/TElocal#1]
Hi Oliver,

Thanks for developing the tool. I have installed TElocal, although I got exactly the identical output as TEcount. I don't think I can distinguish each TE locus by using current TElocal/TEcount output. Do you know where I can find the hits at each TE locus?

Best,
Xun

**Comment by olivertam** [comment]
Hi,
Are you using the same indices from TEtranscripts? You have to use the ones built for TElocal, which are available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/).
Thanks.

**Comment by xunchen85** [comment]
Thanks,

I will try it, BTW, the gene annotation should not matter, right?

**Comment by olivertam** [comment]
Hi,
The gene quantification for TElocal currently functions similarly to TEtranscripts, and can use the same gene GTFs.
Thanks.

**Comment by xunchen85** [comment]
Hi,

Thanks for your prompt response. I will let you know if I have further questions.

Best,

**Comment by xunchen85** [comment]
Hi,

I have one last question. Is there any way how I can define to use our own TE list? If there is any script to convert from GTF/BED to the IND file?

Best,
