### ISSUE TITLE
Zebrafish index for TElocal

### ISSUE THREAD

**Issue by stefaniehoho** [mhammell-laboratory/TElocal#11]
Hi, 

I'm very interested to try TElocal for my zebrafish RNAseq data. However, the TElocal index for zebrafish is not available. I'm wondering if I could ask your help in generating Zv10/GRC10 index.

Thank you very much.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software. We'll start building it, and let you know when it is ready to download.

Thanks.

**Comment by olivertam** [comment]
Hi,

Sorry for the slow response. A pre-built index of the DanRer10 is ready for [download](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/danRer10_rmsk_TE.gtf.locInd). The GTF that was used to generate this is available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/danRer10_rmsk_TE.gtf.gz).

Please check that the chromosome IDs between the GTF and your genome build matches up, and let us know if that's not the genome build that you're using.

Thanks.

**Comment by stefaniehoho** [comment]
Thank you so much for generating this index. 

I will download and try it out. Will let you know if it works.

Much appreciated.

**Comment by wushyer** [comment]
Hi, I want to use this software in another plant. How to build TE index? I already curated the TE gtf files. Thanks

**Comment by olivertam** [comment]
Hi,

I will address your question [here](#17).

Thanks.
