### ISSUE TITLE
GTF index for custom genome/annotation?

### ISSUE THREAD

**Issue by javibio-git** [mhammell-laboratory/TElocal#12]
Hi, 

I am wondering if it is possible to generate an `.ind` file from a custom genome annotation. I have read here that it is possible to simply use the straight GTF file, Is that right? 

I can tell that my GTF file has the exact same format as the one required for TEtranscripts. Would that be enough? 

Thank you. 

Javier

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
It is possible to use the straight GTF file, though it will take some time (up to 2 days for human/mouse) to build the index (this is something that we're still optimizing), and unfortunately will not save it.
Let me talk with other people and see if we could pre-build it for you.

Thanks.

**Comment by javibio-git** [comment]
Thanks for the quick reply! I'd greatly appreciate if you help me to pre-build the TE index file. 

In the meantime, I tried to run TElocal using my standard TE gtf file but I got the following error (seems that it really needs the `.locInd` file): 
`TE annotation file needs to be a TElocal index, which will end in .locInd INFO  @ Mon, 04 Jan 2021 12:02:21:`

The command line I used was: `TElocal -b file.bam --GTF gene.gtf --TE TE.gtf --project test1` Am I doing it right? or Is there anything else I should do to make my gtf file suitable for TElocal?

Thank you.

**Comment by olivertam** [comment]
Oops. Sorry about that.

We recently updated the software to only use the `.locInd` files, so it will need to be pre-built.
If you like, we can build it for you. Let us know if that is acceptable. You will just need to provide your custom TE GTF (I'm not sure what's the best way for you to do so).
We hope to enable users to build their own `.locInd` file in the future.

Thanks.

**Comment by javibio-git** [comment]
Thanks for the clarification.

I wouldn't mind providing you my gtf files. I can send a dropbox link to your e-mail address if that is ok with you. 

Please, let me know.

Thank you.

**Comment by olivertam** [comment]
That would work great.
My email is tam at cshl dot edu
Thanks.

**Comment by javibio-git** [comment]
I just shared the files with you. Please let me know if you have any issues. 

Thank you!

**Comment by olivertam** [comment]
I got them, and will process them as soon as possible.

Thanks.

**Comment by olivertam** [comment]
Hi,

The `.locInd` files have been built (the GTF were small, so it was much quicker).
They can be downloaded [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/private/javibio-git/).
Let us know if you encounter issues with them.

Thanks.

**Comment by javibio-git** [comment]
Great! I really appreciate it. I got them.

Thank you for your help!

**Comment by javibio-git** [comment]
I was able to run TElocal with no issues I think I am going to close this issue and re-open it or create a new one if something comes up. Thank you a lot for all your help.
