### ISSUE TITLE
Creating locInd file with a curated list of insertions

### ISSUE THREAD

**Issue by emattei** [mhammell-laboratory/TElocal#13]
Hi,
I would like to use TElocal with a non-reference list of TE insertions. How can I create my own .locInd file?

Thank you,
Eugenio

**Comment by olivertam** [comment]
Hi Eugenio,

We do have a script that could generate the `.locInd` file, though it is in alpha.
Let me check with the author and see if it can be distributed.
Alternatively, if you only have one/two non-reference TE GTF files, we could potentially generate the `.locInd` file for you.

Thanks for your patience.

**Comment by emattei** [comment]
Hi, 
we need to test several individual loci annotations on different organisms so it is not really convenient.
I hope you would be able to release the script soon.

Thanks

**Comment by olivertam** [comment]
Hi Eugenio,

We're still discussing whether the code is stable enough for limited distribution.
We'll let you know as soon as possible.
Apologies.

Thanks.

**Comment by olivertam** [comment]
Hi Eugenio,

Here's the link to the [TEindexer](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/TEindexer) that should hopefully build the indices for TElocal. It needs to be run in the same environment where you run TElocal, as it depends on the same libraries as that program.

This is the full usage:
```
usage: TEindexer [-h] --afile annotation-file --itype index-type
                 [--project name] [--verbose verbose] [--version]

Building an index for the genome or transposable element annotations file.

optional arguments:
  -h, --help            show this help message and exit
  --afile annotation-file
                        file for indexing of annotations
  --itype index-type    index type to build for this gtf (gene or TE)
  --project name        Prefix for the index file. Default is empty string
  --verbose verbose     Set verbose level. 0: only show critical message, 1:
                        show additional warning message, 2: show process
                        information, 3: show debug messages. DEFAULT:2
  --version             show program's version number and exit

Example: TEindexer --afile gene_annotation.gtf --itype gene
Example: TEindexer --afile TE_annotation.gtf --itype TE
```

The example above is typically what we use. It will create a file with the extension `.locInd` when indexing a TE GTF. Note that this expects a TE GTF in the same style/format as the TEtranscripts GTF file (available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/)).

As we have previously mentioned, this is in _alpha_, and there could be portability issues. Please let us know if you encounter issues, and we can try to help.

Thanks, and good luck.

**Comment by emattei** [comment]
Thank you very much! This is great! Duly noted that is an alpha, I will let you know if there are problems.

**Comment by olivertam** [comment]
Hi Elin,

Thank you for your interest in the software.
We have been moving files around, and the TElocal_indexer is now [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer).
Please note that this is still an alpha.

Thanks.
