### ISSUE TITLE
locInd file for GRCh37

### ISSUE THREAD

**Issue by kiekyon** [mhammell-laboratory/TElocal#15]
Hi,

Can I check if you have a pre-built locInd index for GRCh37? 

Thanks

KK

**Comment by olivertam** [comment]
Hi,

Are you using the GRCh37 genome FASTA from Ensembl (canonical chromosomes are just numbers, e.g. `1`), or is it from GENCODE (canonical chromosomes have `chr` in front, e.g. `chr1`)?
We don't have it currently, but we can start making it.

Thanks

**Comment by kiekyon** [comment]
Hi Oliver, thanks for the kind offer. 

I am using the Ensembl version.

**Comment by olivertam** [comment]
Great.
We are building index now, and will get back to you when it's done.
It might take a couple of days.

Thanks.

**Comment by olivertam** [comment]
Hi,
Sorry for my slow response.
The index for GRCh37 Ensembl is [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/GRCh37_Ensembl_rmsk_TE.gtf.locInd.gz).
Please let me know if you encounter any issues.

Thanks.

**Comment by kiekyon** [comment]
Thanks a lot. The index work well. 

KK
