### ISSUE TITLE
TE index for non-model plant

### ISSUE THREAD

**Issue by wushyer** [mhammell-laboratory/TElocal#17]
Hi I am working on some non-model plant TE. Could I ask how to build the TE index on my own? Or  I send to you ? Thanks.

Best
Shuangyang

**Comment by olivertam** [comment]
Hi Suangyang,

Thank you for your interest in the software.
We have a script that could generate the TElocal index. However, it is in **alpha**, so it may not be completely bug-free.
The script is [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer), and requires `TElocal` to be installed on your system.
Please let us know if you encounter any issue, and we can try to help you with it.

Thanks.

**Comment by wushyer** [comment]
Hi Oliver,

     Many thanks for the share!!! It works in my TE gtf. I will launch the whole pipeline and let you know. Thanks for this help.

Best
Shuangyang
