### ISSUE TITLE
TElocal index

### ISSUE THREAD

**Issue by olivertam** [mhammell-laboratory/TElocal#18]
Dear Oliver Tam,

Thank you for providing very useful software. TEtranscripts and TElocal are the same,  but, in order to run TElocal,  we have to provide,  indexed GTF files. 

Could you show me some example how to generate this file,  I do not have any ideas about this. 

I can also use TEcount instead of TEtranscripts,  and generate only count table alone that can be used for differential analysis. 

the only difference is that TEtrnscripts will peroform differentiall analsis, 

TElocal use indexed GTF file. 

with regards 

Ramky

![image](https://user-images.githubusercontent.com/70749594/144968136-b7face20-9f8d-499e-850f-3deb2af8e7d7.png)

_Originally posted by @Ramkyeri in https://github.com/mhammell-laboratory/TEtranscripts/issues/33#issuecomment-987579062_

**Comment by olivertam** [comment]
Hi

You can generate the pre-built index using the TE GTF that was previously created (the first one).
As mentioned [previously](https://github.com/mhammell-laboratory/TEtranscripts/issues/105), you make the prebuilt index using the [`TElocal_indexer`](https://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer) script (requires `TElocal` to be installed). The command line arguments are as follows:
```
$ TElocal_indexer --afile TE.gtf --itype TE
```
It is advisable to provide around 30Gb of RAM for index building.
Like your previous `TEtranscripts` run, the index building will take a long time (~30 hours, if I recall correctly), but once completed, `TElocal` will just load the index for its run, which will substantially improve run-time.

Just a note: `TElocal` functions similarly to `TEcount`, in that it would not perform the differential analysis, but generate the count tables that you can then combine into a single count table to run your differential analysis.
Please also note that `TEtranscripts` requires [`DESeq2`](https://bioconductor.org/packages/release/bioc/html/DESeq2.html) installed in order to perform differential analysis.

Please let us know if you have other questions.

Thanks

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

Thank you so much for your time and for showing me an example. 

Yes, you are correct,  it 30 hours to build an index. Thank you for remembering. 

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

while running the      TElocal_indexer --afile TE.gtf --itype TE        , it got the error, 

![image](https://user-images.githubusercontent.com/70749594/145184855-5e714644-4b98-4bb7-922a-001ab7ed4e12.png)


with regards

Ramky

**Comment by olivertam** [comment]
Hi Ramky,

You will need to first make the script an executable:
```
$ chmod a+x TElocal_indexer
```
You can then run it from the directory where the script is located:
```
$ ./TElocal_indexer --afile TE.gtf --itype TE
```
Or copy the script to a folder containing your other binaries/executabes (e.g. where you TElocal is installed). This will then allow you run it from anywhere on your system
```
$ TElocal_indexer --afile TE.gtf --itype TE
```

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

Thank you for sharing the script. 

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

I do not why it still shows the error,    

![image](https://user-images.githubusercontent.com/70749594/145332596-6c4030b3-a7f0-400e-8e13-8ce1386487e8.png)

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

I think it is correct,    I used this  ./TElocal_indexer.py --afile TE.gtf --itype TE      (.py)       

![image](https://user-images.githubusercontent.com/70749594/145339836-e7d7ba78-1037-4245-ae3c-16d84425c512.png)

with regards 

Ramky

**Comment by olivertam** [comment]
Hi Ramky,

Yes, it appears the script was saved with the `.py` extension, and thus your solution is correct.

Thanks

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,  

this is just for the update,  TE indexing is completed, it took more than 50 hours.  The output also says that this can be used only in TElocal. 

TElocal do not require whether it is a control sample or treatment sample, 

with regards 

![image](https://user-images.githubusercontent.com/70749594/145702108-0854ee42-4229-4223-8f63-9992657f75a6.png)

**Comment by olivertam** [comment]
Hi Ramky,

As previously mentioned, `TElocal` operates like `TEcount`, and takes only one sample at a time (agnostic to whether treatment or control). You will need to combine the outputs of various `TElocal` run to perform your own differential analysis.

Thanks.

**Comment by Ramkyeri** [comment]
Dear Oliver Tam,

many thanks for your reply.  

with regards 

Ramky

**Comment by Ramkyeri** [comment]
Dear Oliver Tam, 

Greetings! I would like to update the analysis.  I used TE2.gtf fod indexing.  it did not break the program in both TElocal_indexer.py and TElocal. 
with regards
Ramky


![image](https://user-images.githubusercontent.com/70749594/146142827-a9b8bed0-fda7-4825-869e-fe9678e9aba6.png)

**Comment by olivertam** [comment]
Thank you for the update.

**Comment by INTS11** [comment]
Hi Oliver Tam,

I install TElocal with the commond pip install TElocal in conda env. Would you like to tell me where can I find TElocal_indexer?
Thank you,

Pinpin

**Comment by olivertam** [comment]
Hi Pinpin,

The `TElocal_indexer` is still in beta, hence we didn't include with `TElocal`.
You can obtain it [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer)

Thanks.

**Comment by ChiaraGTH** [comment]
Hi Oliver Tam,
would it be possible to have a library where the .locInd files, of the various species, can be downloaded directly? The ones that are there are not up to date, and building index files takes a long time.
Thanks.

**Comment by pabisk** [comment]
Could you add a progress indicator to the indexing script? Since it can take multiple days to run it would be good to know whether it is working or getting stuck and how much time is left until it finishes.

**Comment by olivertam** [comment]
Hi,

We are currently in the process of improving the `TElocal` software to significantly speed up the TE index building process, and thus we are envisioning that the current indexing script will be deprecated.
Therefore, we have no current plans to update the indexing script.

Thanks.

**Comment by watamine** [comment]
Dear Oliver Tam,

Thank you for your software.
I installed TElocal and used `TElocal_indexer`. 
I started 7/20 but now 7/25 building index doesn't finish.

<img width="580" alt="image" src="https://github.com/mhammell-laboratory/TElocal/assets/134268615/44bea24f-f31c-44e7-bbbe-8d5ede67a7f9">

Why is it happened ?
I used `TEtranscripts` index file for `--afile TE.gtf`

I would greatly appreciate it if you could let me know

watamine

**Comment by olivertam** [comment]
Hi watamine,

Thank you for your interest in the software.
Depending on the size of the TE GTF file, it can take quite a while to build that index (days).
If it is still not done after a week, please let us know and we can try to troubleshoot.

Apologies.

**Comment by watamine** [comment]
Hi Oliver Tam,

<img width="615" alt="image" src="https://github.com/mhammell-laboratory/TElocal/assets/134268615/6526d35c-582e-430a-ab83-12db24491e63">

`TElocal_indexer` finished !
Thank you for your advice.

Thanks.
