### ISSUE TITLE
User specified IND file

### ISSUE THREAD

**Issue by xunchen85** [mhammell-laboratory/TElocal#2]
Hi,

I have one last question. Is there any way how I can define to use our own TE list? If there is any script to convert from GTF/BED to the IND file?

Best,

**Comment by olivertam** [comment]
Hi,
Yes, there is a way to use your own TE list, but the script to convert it to IND is not ready for release. Furthermore, our current script takes quite a long time, so we're still trying to see if it can be optimized.
If you have a particular TE list that you would like to use, we can try to help you convert it.
Thanks.

**Comment by xunchen85** [comment]
Thanks, I will let you know if I have a specified TE list that need your help for the conversion.

Best,
