### ISSUE TITLE
output format issue and index error during processing

### ISSUE THREAD

**Issue by jamesc99** [mhammell-laboratory/TElocal#20]
Hi,

Thanks for developing this useful tool!

1. I run TElocal with the BAM file generated from STAR and gtf/gtf.locInd files from your lab web. it showed I have finished the analysis but I noticed an error during the process, and I do not know what did this mean.

`[E::idx_find_and_load] Could not retrieve index file for '.1656346536.1014965bam'`

2. besides, do you have an instruction to explain the output? the only output file I got is the `cntTable` file with only two columns. and I do not know how to explain the results.

![image](https://user-images.githubusercontent.com/81212185/176000447-98af5d49-8cc3-4c25-bca4-51a482078cfe.png)

Any suggestion would be highly appreciated, thanks!

Ryan

**Comment by olivertam** [comment]
Hi Ryan,

The first "error" message is a known "quirk" of pysam (see issue #14), and has no impact on the analysis.
The "cntTable" file is the count table. The first column is the feature (in your example screenshot), Ensembl ID of the genes (the TE are lower in the file). The second column is the count of reads that is assigned to that feature (i.e. how abundant that feature was found in your sample).
Please let us know if that does not address your question.

Thanks.
