### ISSUE TITLE
Treatment v Control

### ISSUE THREAD

**Issue by keroguynes** [mhammell-laboratory/TElocal#21]
Hi, I've tried to obtain count table for treatment v. control but the output seems to merge the all the counts in a single column without delineating sample type. I was able to obtain this using `TEtranscript` and was wondering how to get a similar output with `TElocal`. I would greatly appreciate any input on this. Thanks in advance.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in `TElocal`. 

Unlike `TEtranscripts`, `TElocal` operates like `TEcount` (provided with `TEtranscripts`) and quantifies each library separately. Thus, to generate the combined count table, you will need to run `TElocal` on each library, and then join the output (`xxxx.cntTable`) to make a combined count table.

Please let us know if you have further questions.

Thanks

**Comment by keroguynes** [comment]
Dear Oliver,

Thank you for your quick response. I have generated count tables for each library. Will join the output as per suggestion.

Many thanks again!
