### ISSUE TITLE
Generate the locInd annotation from GTF 

### ISSUE THREAD

**Issue by ZunpengLiu** [mhammell-laboratory/TElocal#24]
Hello,

Thank you very much for developing so cool tools to estimate the repetitive element expression at locus-specific level.

I am interested in some genomic regions which are not annotated by RepeatMasker. And, I am trying to calculate the expression levels for these genomic loci. However, I only have the GTF files and the TElocal may need the locInd file [--TE TE-annot-file           locInd file for transposable element annotations]. Could you please help us generate these files or tell us the strategy how to generate these files?

The GTF files: 
[GTF.zip](https://github.com/mhammell-laboratory/TElocal/files/9388515/GTF.zip)

Many thanks for your help!!!

Best,

Zunpeng

**Comment by olivertam** [comment]
Hi Zunpeng,

Thank you for your interest in the software.
Do you want to create an index that has both the RepeatMasker and your own annotations? This is probably preferable, as you would want to quantify your custom annotations alongside the other TE.
If so, I would recommend the following steps:
```
## You want to exclude overlapping exonic annotations from the RepeatMasker GTF
$ awk '$3=="exon"' hg19_HERV.gtf > hg19_HERV_exons.gtf
## Removing overlapping exons
$ bedtools intersect -s -v -a hg19_rmsk_TE.gtf -b hg19_HERV_exons.gtf > hg19_rmsk_filtered.gtf
## Make your "final" GTF
$ cat hg19_rmsk_filtered.gtf hg19_HERV_exons.gtf | sort -k1,1 -k4,5n > hg19_custom_repeat.gtf
## Run our TElocal indexer (assuming that you have already installed TElocal somewhere on the system). 
## Please note that this can take days to run.
$ ./TElocal_indexer --afile hg19_custom_repeat.gtf --itype TE
```
You can get bedtools [here](https://github.com/arq5x/bedtools2/releases), and our indexer [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer). Our RepeatMasker GTF files are here: ([hg19](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/hg19_rmsk_TE.gtf.gz) and [hg38](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/hg38_rmsk_TE.gtf.gz)).

Let me know if you encounter any issues, and we can help you out further.

Thanks.

**Comment by ZunpengLiu** [comment]
Thank you very much for your kind and prompt reply! Your suggestions are very instructive and helpful!
I will give it a try based on your suggestion.

Best,
Zunpeng
 

> Hi Zunpeng,
> 
> Thank you for your interest in the software. Do you want to create an index that has both the RepeatMasker and your own annotations? This is probably preferable, as you would want to quantify your custom annotations alongside the other TE. If so, I would recommend the following steps:
> 
> ```
> ## You want to exclude overlapping exonic annotations from the RepeatMasker GTF
> $ awk '$3=="exon"' hg19_HERV.gtf > hg19_HERV_exons.gtf
> ## Removing overlapping exons
> $ bedtools intersect -s -v -a hg19_rmsk_TE.gtf -b hg19_HERV_exons.gtf > hg19_rmsk_filtered.gtf
> ## Edit your custom GTF to include tags for family_id and class_id
> $ sed -i 's/repClass/class_id/;s/repFamily/family_id/' hg19_HERV_exons.gtf
> ## Make your "final" GTF
> $ cat hg19_rmsk_filtered.gtf hg19_HERV_exons.gtf | sort -k1,1 -k4,5n > hg19_custom_repeat.gtf
> ## Run our TElocal indexer (assuming that you have already installed TElocal somewhere on the system). 
> ## Please note that this can take days to run.
> $ ./TElocal_indexer --afile hg19_custom_repeat.gtf --itype TE
> ```
> 
> You can get bedtools [here](https://github.com/arq5x/bedtools2/releases), and our indexer [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer). Our RepeatMasker GTF files are here: ([hg19](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/hg19_rmsk_TE.gtf.gz) and [hg38](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/hg38_rmsk_TE.gtf.gz)).
> 
> Let me know if you encounter any issues, and we can help you out further.
> 
> Thanks.
