### ISSUE TITLE
TEcount

### ISSUE THREAD

**Issue by TaoHJiang** [mhammell-laboratory/TElocal#26]
Dear Oliver Tam,

I used TEcount to generate count tables for each sample. Now, I wonder if TEs contribute to transcripts expression, that is, how many reads in the transcript are derived from TE? We collected reads  of TE-gene junctions using leafcutters. The proportion of reads contributed by TE in the transcripts was then calculated. Finally, the differential utilization rates of TEs was obtained by comparig  the proportion difference in different samples. The question is that some  reads from TE-gene junctions was higer than that in transcripts, which is clearly false.  My question is whether it is possible to remove these problematic "ratios" and continue with the subsequent analysis. Although this may not be related to the use of the software itself, I still look forward to your reply.
Thanks!

**Comment by olivertam** [comment]
Hi,

As you can imagine, there might be errors in attribution of TEs to a particular locus, attribution of a gene-derived read to a particular transcript isoform, and non-uniform capture and amplification of different regions along the length of the gene. Each of these may lead to situations where the “uniquely mappable” gene-TE junction reads appear to be more abundant than the reads along the rest of the length of the overall transcript itself (which might also be a transcript length normalization issue). 

In our opinion, I don't think your question could be easily resolved without using long-read sequencing experiments.

Thanks.

**Comment by TaoHJiang** [comment]
Thank you for your wonderful answer.
