### ISSUE TITLE
TElocal and TEcounts 0.0

### ISSUE THREAD

**Issue by ChiaraGTH** [mhammell-laboratory/TElocal#28]
Dear Oliver Tam,

I am trying to use TElocal tool to find to find transposable elements within my sequence alignments.
I have run the following command : 
TElocal --sortByPos --mode uniq -b SEQ40026_sorted.bam --GTF Danio_rerio.GRCz11.109.gtf  --TE /TElocal-master/danRer11_rmsk_TE.gtf.locInd
I downloaded the .locInd file from here: https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/?C=D;O=A
Every time I try, "TE counts total 0.0" appears. And the output table of TElocal contains only 0.  
![Screenshot (867)](https://user-images.githubusercontent.com/131363754/233415775-db3dd6fd-3524-4022-a16a-9e33b02a1955.png)

Do you know how I can solve this problem? 

Thank you so much.

**Comment by ChiaraGTH** [comment]
Thank you very much, 
If I use the GTF file you provided, TE count works perfectly.

**Comment by olivertam** [comment]
The prebuilt TElocal index for GRCz11 is ready, and can be downloaded [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/GRCz11_Ensembl_rmsk_TE.gtf.locInd.gz)
