### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by xunchen85** [mhammell-laboratory/TElocal#3]
Hi,

Do you know how I can retrieve the coordinates for each locus?

I found the names for each locus is similar to the repeats generated by repeatmasker (the input for the TEcount). Although I found the names are not the same.

Thanks,
Xun

**Comment by olivertam** [comment]
Hi,

We may have a few of the GTF [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/GTF/) that were used to generate the indices.
Please let us know if they are not matching up.

Thanks.

**Comment by xunchen85** [comment]
Thanks,

I found out that the first character of the TE name will be removed in the output. I will check if there is any issues with my codes. 

Thanks
