### ISSUE TITLE
GRCh39 ensemble

### ISSUE THREAD

**Issue by songlyzz** [mhammell-laboratory/TElocal#31]
Dear Oliver Tam,
Hi
  I would like to download GRCm39 from https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/?C=D;O=A
，but there is only gencode GRCm39,  I am fraid that it is not match the ensemble GRCm39 gene GTF, could you please offer me the reference locInd file?
THANK YOU !

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
We are now generating the GRCm39 Ensembl TE index, and will let you know once that this ready.

Thanks.

**Comment by 13996063883** [comment]
Hi ，Oliver Tam
  I understand it ! 
  Thank you very much!

**Comment by olivertam** [comment]
Hi,

The index for [GRCm39 Ensembl](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/GRCm39_Ensembl_rmsk_TE.gtf.locInd.gz) is ready.

Thanks
