### ISSUE TITLE
how to speed up

### ISSUE THREAD

**Issue by AlisaGU** [mhammell-laboratory/TElocal#32]
Hi, just like the title, is there a way to speed up TElocal?

I am building the index of TE annotation, so no clear concept about the running time. 
However, my genome is big and RNA-seq bam is about 40G. The running time is definitely long.

Could you give me some tips in preparation for the counting step?

**Comment by AlisaGU** [comment]
Wow, so quick a reply!

There are 60108975 TE in the genome. Can I split it into several files to build index and count reads separately?

**Comment by AlisaGU** [comment]
OK~, thanks for your quick and detailed answer.

**Comment by AlisaGU** [comment]
Hi, my index program has running for 7 days and 18hour without any result output. Is it normal?

This is my code:
```
$TElocal_indexer --afile DN.denovo.RepeatMasker.Telocal.gtf --itype TE
```

**Comment by olivertam** [comment]
Hi,

Unfortunately, depending on how big your TE GTF file is, the indexing step takes quite a while. I'm afraid it could take more days still.
We are currently developing a version of `TElocal` that could bypass/speed up this step.

Thanks.

**Comment by AlisaGU** [comment]
Is it expected that no result was outputted during the process?

**Comment by olivertam** [comment]
Unfortunately, yes, because everything is being processed in memory.
We had considered improving the logging, but this was technically a script that we were using in-house, and with our efforts going towards removing the index requirement, we decided not to add more to the indexing script.

Thanks.

**Comment by AlisaGU** [comment]
Thanks for your continuous efforts! Looking forward to using the improved version!
