### ISSUE TITLE
TE duplicate numbers

### ISSUE THREAD

**Issue by sophiemarlow** [mhammell-laboratory/TElocal#34]
Hi there, 
Thanks very much for creating this software, I have been enjoying using it. 

I have my counts table and have been conducting some differential expression analysis using edgeR and I have noticed individual duplicate names are given, IAPEY4-I-dup351 as an example. As these individual duplicates are not in the original TE GTF file I was just wondering how they come about.

I was also wondering whether there would be a way of relating back the chromosome position of the TEs given in the GTF file to the names of the TEs given in the counts table generated by TE local. I have been using the GRCm39 Ensembl TE GTF that you have created.

Many thanks in advance.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.

The "duplicate" names are the name for the individual insertion of that subfamily. E.g. `IAPEY4-I-dup351` is the 352nd (351st duplicate) of the IAPEY4 internal sequence identified in the genome. The names are actually in the `transcript_id` section of the corresponding GTF (e.g. GRCm39 Ensembl TE GTF).

Regarding the genomic position, you should be able to find it [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/annotation_tables/GRCm39_Ensembl_rmsk_TE.gtf.locInd.locations.gz). If not, it should also be in the [TE GTF](https://labshare.cshl.edu/shares/mhammelllab/www-data/TEtranscripts/TE_GTF/GRCm39_Ensembl_rmsk_TE.gtf.gz).

Please let us know if you encounter any issues.

Thanks.

**Comment by sophiemarlow** [comment]
That's great, thank you very much! I was also wondering whether there is a way that you'd recommend to view the TEs from the GTF in a genome browser, I have been trying with UCSC but I have been having a few formatting issues with the GTF. Many thanks.

**Comment by olivertam** [comment]
Hi,

Actually, the TE GTF is derived from the UCSC RepeatMasker track (mm39), so you could use that track as a proxy for the TE GTF.
Alternatively, if you're using Ensembl-based annotations, we would recommend [IGV](https://www.igv.org/) as a way to visualize the data.

Thanks.

**Comment by sophiemarlow** [comment]
Thanks very much for your advice, using the UCSC RepeatMasker track works very nicely!
