### ISSUE TITLE
Error attempting to load .locInd file

### ISSUE THREAD

**Issue by Kiliankleemann** [mhammell-laboratory/TElocal#36]
Dear Oliver Tam,

I downloaded the Gencode_rmsk_TE.locInd.locations file and tried TElocal but I get: Error attempting to load ...locInd

I tried adding the .locations again or removing but that didnt work. 

Do you have anys suggestions?

Kind regards
kilian

**Comment by Kiliankleemann** [comment]
Thank you Oliver, that was simple fix :)

**Comment by Nakyung210** [comment]
Hi,

Thank you for the amazing software! I got similar error, but I used `GRCh38_GENCODE_rmsk_TE.gtf.locInd`.

I've trying to run TElocal with `TElocal --sortByPos --mode multi -b ${sample_id}.sortedByCoord.bam --GTF gencode.v45.annotation.gtf --TE GRCh38_GENCODE_rmsk_TE.gtf.locInd --project ${sample_id}`. I downloaded `GRCh38_GENCODE_rmsk_TE.gtf.locInd` file from your lab's Dropbox: https://www.dropbox.com/scl/fo/ns27xr753yhvwgocyl846/AIAMyK6E56dGeuBuYnnHoxc/prebuilt_indices?dl=0&rlkey=d8l7yl1dezih5hqvjjywih0v1&subfolder_nav_tracking=1

But I encountered following error message while running: 
CRITICAL @ Sat, 15 Aug 2026 19:32:42: Error attempting to load /rsrch5/scratch/mol_cgenesis/noh/reference/TElocal/GRCh38_GENCODE_rmsk_TE.gtf.locInd

Could you help me figure out how to solve this issue?

Thank you in advance!
Nakyung

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
Based on the code, it appears that it found the file based on the file path and name, but could not load it.
Could you confirm that you decompressed the downloaded file? The `md5` for the `locInd` file is `740caecc9c33932a09c5230310e6e0a9`
Could you also confirm that you have read access to that file, and that you allowed sufficient memory (~10Gb) for the index to load?
I tested loading the `locInd` file on my end, and it appeared to load properly.

Thanks.

**Comment by Nakyung210** [comment]
Thank you so much, it was simply solved by `chmod u+r GRCh38_GENCODE_rmsk_TE.gtf.locInd` as you suggested! Also, my downloaded `md5sum GRCh38_GENCODE_rmsk_TE.gtf.locInd` matched with `740caecc9c33932a09c5230310e6e0a9`. 

Thank you again for the help!
