### ISSUE TITLE
Can I apply TElocal to Single End Sequencing 

### ISSUE THREAD

**Issue by smarhon** [mhammell-laboratory/TElocal#37]
Hi

Can I apply TElocal to single end sequencing?

Thanks

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
Yes, you can use TElocal with single end libraries.

Thanks.

**Comment by smarhon** [comment]
> Hi,
> 
> Thank you for your interest in the software. Yes, you can use TElocal with single end libraries.
> 
> Thanks.

Thank you so much.

Is there a tool that I can use to create my own index to use with TElocal tool? Or can I send you a GTF file and you create it form me?


Best
Sajid

**Comment by olivertam** [comment]
Hi,

The [`TElocal_indexer`](https://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer) is available. It is in beta, and may be deprecated in a future version of TElocal, but could be used now.
Please note that it will take quite a while to generate the index if your TE annotation is large.

Thanks.

**Comment by olivertam** [comment]
Hi,

Our pre-built indices are for the TE, not the gene. You can also pre-built the gene index with the tool, but it's not required by `TElocal`.
Thanks.

Cheers,
Oliver

**Comment by smarhon** [comment]
> Hi,
> 
> Our pre-built indices are for the TE, not the gene. You can also pre-built the gene index with the tool, but it's not required by `TElocal`. Thanks.
> 
> Cheers, Oliver

Thank you for your prompt response!

When I use your prebuilt index, it quantifies reads for genes and TEs. 
https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/hg38_rmsk_TE.gtf.locInd.gz

Am I am using the correct index?

Best
Sajid

**Comment by olivertam** [comment]
Hi,

Could you provide the command line?
You have to provide both a gene GTF (`--GTF`) and a TE index (`--TE`), so you will quantify both genes and TEs. It is actually crucial to quantify both at the same time, as "overlaps" between the two annotation sets are resolved differently depending on whether the read is uniquely or ambiguously mapped.

Thanks.

**Comment by smarhon** [comment]
> Hi,
> 
> Could you provide the command line? You have to provide both a gene GTF (`--GTF`) and a TE index (`--TE`), so you will quantify both genes and TEs. It is actually crucial to quantify both at the same time, as "overlaps" between the two annotation sets are resolved differently depending on whether the read is uniquely or ambiguously mapped.
> 
> Thanks.

Sorry about that. 
Yes, because I am using both --GTF and  --TE options. I did not pay attention to this.
Thank you for the clarification.
