### ISSUE TITLE
Docker container?

### ISSUE THREAD

**Issue by R-Najjar** [mhammell-laboratory/TElocal#40]
Hello,
Is there a docker container for TElocal? 

Thank you

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
Currently, there is no Docker container for TElocal.
We can look into adding one.

Thanks.

**Comment by olivertam** [comment]
Could you try this and let us know if it works?
```
docker pull mhammelllab/telocal
```

**Comment by olivertam** [comment]
Hi,

I think this is because the current Docker installed TElocal from `setup.py`, versus using pip to install.
However, looking at the log, it appears to have completed successfully.
Could you check that the output count table is present? If so, I might ignore that warning message.

Thanks.

**Comment by R-Najjar** [comment]
Yes, the output table is present. Thank you again for creating the container so quickly.
