### ISSUE TITLE
Adding additional transposable elements to annotation file

### ISSUE THREAD

**Issue by R-Najjar** [mhammell-laboratory/TElocal#41]
Hello,
I'd like to search for expression of certain transposable elements that are not in the reference. I added their sequences to the reference fasta, and will see what (if any) aligns to them (using bedtools). If I want to quantify them with TElocal, I will need to also add information about them to the annotation locInd file, correct? How would this work?

Thank you

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
If you really want to use TElocal in this manner, then I would add their annotation to the TE GTF of your genome build as though their reference sequence is another chromosome.
For example:
```
nonRefTEseqID    custom    exon    1    6500    .    +    .     gene_id "nonRefTE"; transcript_id "nonRefTE_copy1"; family_id "nonRefTE_family"; class_id "nonRefTE_class"
```
You would then need to build the `locInd` file yourself using [`TElocal_indexer`](https://labshare.cshl.edu/shares/mhammelllab/www-data/private/TEindexer/TElocal_indexer). Depending on the size of TE GTF, it could take many days.

Please let me know if this did not address your question.

Thanks.

**Comment by R-Najjar** [comment]
Thank you Oliver. This makes sense to me
