### ISSUE TITLE
TElocal_indexer 

### ISSUE THREAD

**Issue by zhangqc723** [mhammell-laboratory/TElocal#47]
Hello,
  I want to use TElocal and I can not find the locInd file for mm9. Now, I downloaded a file named **mm9_rmsk_TElocus.ind.gz** from  https://www.dropbox.com/scl/fo/o0my0l1c7s40un9qv6yvf/AC8F4xbB-V3SGcwzMeJ8vG0?rlkey=sbsb00bbcrq4ofmq1oviy7ws1&e=1&dl=0, is this document suitable for me? Besides, I run **./TElocal_indexer** by TE_GTF file, Is it normal for this program to take more than a day and still not be finished?

**Comment by olivertam** [comment]
Hi,

Thanks for your interest in the software.
Since mm9 is two releases behind the latest mouse genome (mm39), we have archived the TElocal prebuilt index.
It is now available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/archive/mm9_rmsk_TE.gtf.locInd.gz).

Unfortunately, TElocal_indexer takes a very long time to build those indices (>3 days for mouse). We hope to remove that requirement soon.

Thanks.

**Comment by zhangqc723** [comment]
Thanks for your patient reply and developing such a useful tool, I will run TElocal with index of GTF provided by you. Thanks you again.

**Comment by zhangqc723** [comment]
> Hi,
> 
> Thanks for your interest in the software. Since mm9 is two releases behind the latest mouse genome (mm39), we have archived the TElocal prebuilt index. It is now available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/archive/mm9_rmsk_TE.gtf.locInd.gz).
> 
> Unfortunately, TElocal_indexer takes a very long time to build those indices (>3 days for mouse). We hope to remove that requirement soon.
> 
> Thanks.

Thanks for your reply, Now I downloaded the TElocal prebuilt index from the link. And I found the names of TEs were mixed in the result of TElocal. For example, the **MamRep1161** belongs to _TcMar_ and _Tigger_ family. But in my TE GTF file, it belongs to _TcMar_ family, Could you explain it? Thanks! 

![image](https://github.com/mhammell-laboratory/TElocal/assets/86176443/bdf20a80-27da-4d58-b15c-716991cbe738)

**Comment by olivertam** [comment]
Hi,

This is due to the annotation in UCSC RepeatMasker being inconsistent at times. This was raised with the UCSC crew, and appears to affect the older genome builds more.

Thanks.

**Comment by zhangqc723** [comment]
> This is due to the annotation in UCSC RepeatMasker being inconsistent at times. This was raised with the UCSC crew, and appears to affect the older genome builds more. It might have been resolved in a more recent GTF update, but since it's a older genome build, we have not re-built the index.
> 
> Thanks.

Thanks for your reply.

**Comment by kamari-weaver** [comment]
Any idea where to find the locInd for mm39?

**Comment by olivertam** [comment]
Hi,

Feel free to browse [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/).

Thanks
