### ISSUE TITLE
Normalisation methods

### ISSUE THREAD

**Issue by anna-elisabet** [mhammell-laboratory/TElocal#48]
Hello,

I have performed TElocal for many different samples across 3 tissue types. My next task is to assess the correlation in read count number between TEs and genes. Before I can do this, I need to normalise the read counts. 
I was thinking I need a normalisation method that would account for differences in "gene length" (also considering the differences in length between genes and TEs), since I will compare read counts within tissue type, not across tissue types.

Let me know if you have recommendations regarding this.
Thank you.

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
We don't have a lot of experience in this, but one approach could be to take the length of the TE instance length as the equivalent "gene length" for TE, and process them as you would for RPKM/FPKM approaches.
If you need the genomic coordinates (and thus length) of the TE instances in our pre-built indices, they are available [here](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/annotation_tables/).

Let us know if there's anything else we can help with.

Thanks.
