### ISSUE TITLE
Output from TElocal

### ISSUE THREAD

**Issue by sanhe374** [mhammell-laboratory/TElocal#49]
I am running TElocal on my samples and the output printed looks like this:

Example output
Total annotated reads = 51491391.34884873
Total non-uniquely mapped reads = 6505093
Total unannotated reads = 14835908

In the total annotated reads there is a . Is there any particular reason why it appears like this here but not for the unannotated or non-uniquely mapped reads?

**Comment by olivertam** [comment]
Hi,

This is due to the EM redistribution, which could end up with fractional counts as part of the calculations. However, these are typically rounded to integers for the final output.

Thanks.

**Comment by sanhe374** [comment]
Thank you!
