### ISSUE TITLE
How to build ind database?

### ISSUE THREAD

**Issue by xunchen85** [mhammell-laboratory/TElocal#5]
Hi,

I'm wondering if there is a script that we can use to convert GTF file to ind file?

I need ind files for multiple species, like panTro6.

Thanks for your help.

**Comment by olivertam** [comment]
Hi,

The tool to build the index is currently still in development, and takes days to build the `.ind` files from the GTF.
In theory, you can use the GTF files in place of the `.ind` files, which will build the index for your analysis (which will still take days), but would (unfortunately) not save the index. However, if you wish to provide us a set of genome builds (preferably those with repeatMasker tracks on UCSC), we can try to build the indices for you.

Thanks.

**Comment by xunchen85** [comment]
How I can share with you the GTF files? I got them from UCSC, they are all repeatmasker output files.

What is your email address? Maybe you can email me (xchen@outlook.com) and I will reply you with the onedrive or google drive link. 

Thanks again for your help.

Xun

**Comment by olivertam** [comment]
Hi Xun,

Are they just unmodified UCSC repeatMasker output? If so, you just need to provide the genome build, and we can try to generate the index.
If they are customized, then feel free to email me at tam at cshl dot edu to provide the links to the files, and we can try to process them.

Thanks.

**Comment by xunchen85** [comment]
Hi Oliver,

I may need the indexes of genome builds for testing, include mm10, ponAbe3, panPan2, panTro6, nasLar1, and rheMac10.

You could get the repeatmasker output from the UCSC webpage: http://hgdownload.soe.ucsc.edu/downloads.html. 

Really appreciate for your help.

Xun

**Comment by olivertam** [comment]
Hi Xun,
We will start working on them, and let you once they are done.
Thanks.

**Comment by olivertam** [comment]
Hi Xun,

The following indices have been built, and are available [here](http://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/):

- nasLar1
- panPan2
- panTro6
- ponAbe3
- rheMac10

Thanks

**Comment by xunchen85** [comment]
Hi Oliver,

I have started getting the files. Thanks so much for your help.

Thanks,
Xun
