### ISSUE TITLE
Source of pre-built GTF indices for T2T human genome

### ISSUE THREAD

**Issue by dprokopov** [mhammell-laboratory/TElocal#50]
Hello,

I would like to know the source of the data used to prepare the pre-built GTF indices for the T2T human genome. The annotations for this genome from UCSC and from the T2T V2 paper (available on GitHub https://github.com/marbl/CHM13) differ significantly. It's crucial for my work to understand which source was used for GTF indexing.

Thank you!

**Comment by olivertam** [comment]
Hi,

Thank you for your question.
We are using the T2T v2 paper annotation for the [prebulit index](https://labshare.cshl.edu/shares/mhammelllab/www-data/TElocal/prebuilt_indices/T2T-CHM13v2_rmsk_TE.gtf.locInd.gz). If you need the hs1 (UCSC T2T version), we can try to generate it.

Thanks

**Comment by dprokopov** [comment]
Thank you for the clarification. The T2T v2 paper annotation is sufficient for my needs, so there's no need to generate a new index.

Thanks again!
