### ISSUE TITLE
Error in building gene index 

### ISSUE THREAD

**Issue by whiteorchid** [mhammell-laboratory/TElocal#9]
Hi, 

May I know "Error in building gene index" is caused by the gene gtf file, which I used : ftp://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_34/gencode.v34.primary_assembly.annotation.gtf.gz

Thanks!

log file content as below:
```
INFO  @ Mon, 10 Aug 2020 11:39:51: 
# ARGUMENTS LIST:
# name = test
# BAM file = test.bam
# GTF file = gencode.v34.primary_assembly.annotation.gtf 
# TE file = hg38_rmsk_TE.gtf.locInd 
# multi-mapper mode = multi 
# stranded = reverse 
# number of iteration = 100
# Alignments grouped by read ID = False

 
INFO  @ Mon, 10 Aug 2020 11:39:51: Processing annotation files ...
 
INFO  @ Mon, 10 Aug 2020 11:39:51: Building gene index ....... 
 
Error in building gene index 
```

**Comment by olivertam** [comment]
Hi,

Thank you for your interest in the software.
We are now taking a look at the error and see if we can replicate it.
Could you confirm that the version of TElocal is 1.1.0?

Thanks.

**Comment by whiteorchid** [comment]
Thanks,

Yes, the version used is TElocal 1.1.0, thanks a lot!

**Comment by olivertam** [comment]
Thanks for your quick response.
I have another question (apologies): which python version are you using?
All the best.

**Comment by whiteorchid** [comment]
python 2.7.15, thanks!

**Comment by olivertam** [comment]
Thanks.
We have been able to replicate the issue, and are now looking into it.
We'll let you know once we have a solution.

**Comment by whiteorchid** [comment]
Thanks so much, appreciate!

**Comment by talithaforcier** [comment]
Hi! Thanks for the information, it looks like there was an extra call for the strandedness parameter, and with that removed it should build the index properly.
